# This is a basic workflow to help you get started with Actions

name: Ferrytime Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [push]
  # schedule:
  # - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scraping_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Scraper

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2

      - name: Scrape site
        uses: ./ # Uses an action in the root directory
        id: hello

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sailings.json
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
